name: Run script
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run test
        run: ./run-test.sh
